spring.application.name=LokiGameBackend
server.port=8080

# Database Config
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lokigame}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=loki
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# Redis Config
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.timeout=60000

# Docker Optimization (Optional)
spring.main.lazy-initialization=true

# Force Hibernate to group 50 separate database queries into 1 single network packet.
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# Games are "bursty." If 1,000 players login at 7:00 PM, a default connection pool might choke. The leak-detection-threshold is a lifesaver for finding "stuck" game simulations.
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=5
# Alerts you if a battle sim takes > 60s (bug!)
spring.datasource.hikari.leak-detection-threshold=60000

# Rate Limiting (Anti-Cheat Foundation)
#app.rate-limit.enabled=true
#app.rate-limit.rules.auth.max-requests=5
#app.rate-limit.rules.auth.window=PT1M # 5 login attempts per minute
#app.rate-limit.rules.default.max-requests=1000 # 1000 API calls per hour per user

# 24 Hours for Access Token (Mobile games usually have long sessions)
jwt.expiration=86400000
# 7 Days for Refresh Token
jwt.refresh-expiration=604800000
# IMPORTANT: Move this secret to an ENV variable in Production!
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

spring.jackson.time-zone=UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC